package tn.esprit.espritgather.enumeration;


public enum EventSkill {
    GESTION_LOGISTIQUE,
    PROMOTION_ET_MARKETING,
    ANIMATION_ET_DIVERTISSEMENT,
    GESTION_DES_PARTICIPANTS,
    COLLECTE_DE_FONDS,
    GESTION_DES_VOLONTAIRES,
    GESTION_DES_SPECTACLES,
    PLANIFICATION_STRATEGIQUE,
    COORDINATION_DES_EQUIPES,
    NEGOCIATION_DES_PARTENARIATS,
    SECURITE_ET_SAUVEGARDE,
    GESTION_DES_COMMUNICATIONS,
    ANALYSE_DES_RETROACTIONS;


}
