package tn.esprit.espritgather.enumeration;

public enum Skill {
    WRITTEN_COMMUNICATION,
    ORAL_COMMUNICATION,
    TEAMWORK,
    COLLABORATION,
    PROJECT_MANAGEMENT,
    PROBLEM_SOLVING,
    ADAPTABILITY,
    QUICK_LEARNING,
    CREATIVITY,
    INNOVATION,
    TIME_MANAGEMENT,
    PRIORITIZATION,
    MARKETING_COMMUNICATION,
    FINANCE_ACCOUNTING,
    HUMAN_RESOURCES,
    ENGINEERING_CONSTRUCTION
}
